apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "asdo.fullname" . }}-api-config
data:
  ASDO_API_OTLP_ENDPOINT: {{ default (printf "http://%s-otel-collector:%v/v1/traces" (include "asdo.fullname" .) .Values.otelCollector.service.otlpHttpPort) .Values.api.otlpEndpoint | quote }}
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
