apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "asdo.fullname" . }}-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "asdo.fullname" . }}-web
automountServiceAccountToken: false
