apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "asdo.fullname" . }}-web-config
data:
  NEXT_PUBLIC_ASDO_API_BASE_URL: {{ .Values.web.publicApiBaseUrl | quote }}
{{- range $key, $value := .Values.web.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
