"use client";

import type { PatchApplicationResult, PatchProposal } from "@asdo/contracts";
import { DiffViewer } from "@asdo/ui";
import React, { useState } from "react";

const INITIAL_PROPOSALS: PatchProposal[] = [
  {
    id: "patch-001",
    organization_id: "018f0000-0000-7000-8000-000000000001",
    work_package_id: "pkg-auth-session",
    summary: "Add secure session token refreshing with exponential backoff",
    digest_sha256: "7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
    files: [
      {
        path: "src/auth/session.ts",
        operation: "modify",
        hunks: [
          {
            old_start: 12,
            old_lines: 3,
            new_start: 12,
            new_lines: 5,
            lines: [
              " export async function getSession() {",
              "-  return cachedSession;",
              "+  if (isExpired(cachedSession)) {",
              "+    return refreshSessionWithBackoff();",
              "+  }",
              "+  return cachedSession;",
            ],
          },
        ],
      },
      {
        path: "src/auth/backoff.ts",
        operation: "add",
        hunks: [
          {
            old_start: 0,
            old_lines: 0,
            new_start: 1,
            new_lines: 4,
            lines: [
              "+export function calculateBackoff(attempt: number): number {",
              "+  return Math.min(1000 * Math.pow(2, attempt), 30000);",
              "+}",
            ],
          },
        ],
      },
    ],
    created_at: "2026-08-20T14:30:00.000Z",
  },
  {
    id: "patch-002",
    organization_id: "018f0000-0000-7000-8000-000000000001",
    work_package_id: "pkg-rate-limits",
    summary: "Add rate limiting headers to health API",
    digest_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    files: [
      {
        path: "src/health.ts",
        operation: "modify",
        hunks: [
          {
            old_start: 1,
            old_lines: 1,
            new_start: 1,
            new_lines: 2,
            lines: [
              " import { Router } from 'express';",
              "+import { rateLimit } from './rate-limit';",
            ],
          },
        ],
      },
    ],
    created_at: "2026-08-20T14:45:00.000Z",
  },
];

export default function PatchesPage() {
  const [proposals] = useState<PatchProposal[]>(INITIAL_PROPOSALS);
  const [selectedProposalId, setSelectedProposalId] = useState<string>("patch-001");
  const [isApplying, setIsApplying] = useState(false);

  const selectedProposal = proposals.find((p) => p.id === selectedProposalId) ?? proposals[0];

  const handleApplyPatch = async (proposalId: string): Promise<PatchApplicationResult> => {
    setIsApplying(true);
    // Simulate patch application against workspace
    await new Promise((resolve) => setTimeout(resolve, 300));
    setIsApplying(false);
    return {
      proposal_id: proposalId,
      applied: true,
      conflicts: [],
      committed_sha: "a1b2c3d4e5f67890123456789abcdef012345678",
    };
  };

  return (
    <div className="flex min-h-screen flex-col bg-slate-950 px-6 py-8 text-slate-100 lg:px-12">
      {/* Header */}
      <div className="mb-8 flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-6">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-3xl font-extrabold tracking-tight text-white">
              Content-Addressed Patches
            </h1>
            <span className="rounded-full bg-cyan-950/80 px-3 py-1 text-xs font-semibold text-cyan-300 border border-cyan-700/50">
              Phase 3C
            </span>
          </div>
          <p className="mt-1.5 text-sm text-slate-400">
            Immutable, SHA-256 bound patch proposals generated by autonomous coding agents.
          </p>
        </div>
      </div>

      {/* Main Layout */}
      <div className="grid grid-cols-1 gap-8 lg:grid-cols-4">
        {/* Proposals Sidebar */}
        <div className="flex flex-col gap-3 rounded-xl border border-slate-800 bg-slate-900/50 p-4 lg:col-span-1">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
            Patch Proposals ({proposals.length})
          </h2>
          <div className="flex flex-col gap-2">
            {proposals.map((p) => (
              <button
                key={p.id}
                type="button"
                data-testid={`proposal-card-${p.id}`}
                onClick={() => {
                  setSelectedProposalId(p.id);
                }}
                className={`flex flex-col gap-1.5 rounded-lg p-3 text-left transition-all ${
                  selectedProposalId === p.id
                    ? "bg-slate-800 border border-cyan-500/40 shadow-md"
                    : "bg-slate-950/60 border border-slate-800/80 hover:bg-slate-800/60"
                }`}
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="text-xs font-bold text-cyan-300">{p.work_package_id}</span>
                  <span className="text-[10px] font-mono text-slate-500">
                    {p.files.length} {p.files.length === 1 ? "file" : "files"}
                  </span>
                </div>
                <div className="text-xs font-medium text-slate-200 line-clamp-2">{p.summary}</div>
                <div className="text-[10px] font-mono text-slate-400">
                  sha256:{p.digest_sha256.slice(0, 10)}...
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Diff Viewer Area */}
        <div className="lg:col-span-3">
          {selectedProposal ? (
            <DiffViewer
              proposal={selectedProposal}
              onApply={handleApplyPatch}
              isApplying={isApplying}
            />
          ) : (
            <div className="flex h-64 items-center justify-center rounded-xl border border-dashed border-slate-800 text-sm text-slate-500">
              No patch proposal selected.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
